Доработана функциональность по ТЗ 6
GretaSovizkaya/TaskManager pull request #1
Opened 2024-05-12 13:35 UTC by GretaSovizkaya

2024-05-13 15:27 UTC, andrew-larkin requested changes
Привет! Очень хорошая реализация, корректная архитектура. В паре мест нужно выполнить небольшой рефакторинг и поправить тесты.

2024-05-13 15:27 UTC, andrew-larkin commented on src/test/InMemoryTaskManagerTest.java
> +    public void shouldSavePreviousVersionOfTaskInHistoryManager() {
падает с ошибкой если запустить сразу все тесты

2024-05-13 15:27 UTC, andrew-larkin commented on src/test/HistoryManagerTest.java
> +class HistoryManagerTest { //добавила тесты
отлично!

2024-05-13 15:27 UTC, andrew-larkin commented on src/managers/InMemoryTaskManager.java
> +
пустые строки удаляем

2024-05-13 15:27 UTC, andrew-larkin commented on src/managers/InMemoryTaskManager.java
> +
этот конструктор удаляем - нам не нужно передавать конкретный HistoryManager

2024-05-13 15:27 UTC, andrew-larkin commented on src/managers/InMemoryTaskManager.java
>          this(Managers.getDefaultHistory());
this.historyManager = Managers...

2024-05-13 15:27 UTC, andrew-larkin commented on src/managers/InMemoryTaskManager.java
> +    public List<Task> getTasks() {
наверное, все-таки лучше оставить как getHistory(), потому что метод возвращает не задачи, а историю просмотров

2024-05-14 06:37 UTC, GretaSovizkaya commented on src/managers/InMemoryTaskManager.java
> +
+

2024-05-14 06:37 UTC, GretaSovizkaya commented on src/managers/InMemoryTaskManager.java
> +
+

2024-05-14 06:37 UTC, GretaSovizkaya commented on src/managers/InMemoryTaskManager.java
>          this(Managers.getDefaultHistory());
+

2024-05-14 06:37 UTC, GretaSovizkaya commented on src/managers/InMemoryTaskManager.java
> +    public List<Task> getTasks() {
Исправлено

2024-05-14 06:38 UTC, GretaSovizkaya commented on src/test/InMemoryTaskManagerTest.java
> +    public void shouldSavePreviousVersionOfTaskInHistoryManager() {
Не знаю, правильно ли сделала, но я предпочла убрать этот тест, так как уже есть тесты на проверку дубликатов и на повторные ID.

2024-05-14 15:41 UTC, andrew-larkin requested changes
Привет! Вернулся к прошлому заданию, которое я не проверял и обнаружил ошибки. Надо поправить.

2024-05-14 15:41 UTC, andrew-larkin commented on src/basis/Epic.java
id не нужно передавать, он назначается в методе createNewEpic

2024-05-14 15:41 UTC, andrew-larkin commented on src/basis/Subtask.java
>  public class Subtask extends Task {
в конструкторе не нужно передавать id - он назначается в методе createNewSubtask

2024-05-14 15:41 UTC, andrew-larkin commented on src/managers/InMemoryTaskManager.java
> +    @Override
1) должен быть приватным; 2) не работает. статус эпика напрямую зависит от статусов сабтасков. любое изменение сабтасков должно включать в себя проверку статуса эпика и его изменение (по требованию)

2024-05-14 15:41 UTC, andrew-larkin commented on src/managers/InMemoryTaskManager.java
> +    @Override
отсутствуют методы update для epic и subtask

2024-05-15 05:06 UTC, GretaSovizkaya commented on src/basis/Epic.java
Исправлено

2024-05-15 05:06 UTC, GretaSovizkaya commented on src/basis/Subtask.java
>  public class Subtask extends Task {
Исправлено

2024-05-15 05:09 UTC, GretaSovizkaya commented on src/managers/InMemoryTaskManager.java
> +    @Override
Честно говоря кроме приватности не совсем поняла, я так понимаю нужно добавить в метод еще и проверку на изменение статуса? У нас же автоматическое изменение происходит через методы обновления, или неправильно понимаю?

2024-05-15 05:09 UTC, GretaSovizkaya commented on src/managers/InMemoryTaskManager.java
> +    @Override
Сделала

2024-05-15 07:20 UTC, GretaSovizkaya commented on src/managers/InMemoryTaskManager.java
> +    @Override
Ваше сообщение с тестовым скриптом у меня загрузилось только после отправки 3 попытки!(
Сразу момент к нему: 
"распечатка должна давать 1 NEW, 2-3 IN_PROGRESS, 4 DONE"
Но у нас в распечатке присваивается статусы в порядке: NEW, IN_PROGRESS_, DONE, DONE. Соответственно вывод такой же, а не NEW, IN_PROGRESS, IN_PROGRESS, DONE. 
Если так и должно быть, направлю Вам сразу с данным скриптом.

2025-03-09 16:02 UTC, closed without merging